### ISSUE TITLE
First draft of drone architecture document and README

### ISSUE THREAD

**Issue by dlebauer** [terraref/drone-pipeline#10]
Can leverage information in this folder https://drive.google.com/drive/u/0/folders/198KRJpaHhwRNhlIkONKfc5-TqKX3ToAm

Include basic workflow, options, user stories, review of existing pipelines

**Comment by Chris-Schnaufer** [comment]
Done: We have OSF site, Google Drive, TERRA REF ticketing, a separate GitHub project with a Wiki.

**Comment by dlebauer** [comment]
Only the [README](https://github.com/terraref/drone-pipeline/blob/master/README.md) is still mostly blank; perhaps put links / summary in the README?

**Comment by dlebauer** [comment]
README will be updated by a PR; making sure it is okay goes here: https://github.com/az-digitalag/organization/issues/36
