### ISSUE TITLE
Port TR extractors to extractor template

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/drone-pipeline#100]
- [x] Metadata Cleaner
- [x] bin2Tiff
- [x] soil mask
- [x] fullfield RGB
- [ ] ~plot clip~
- [x] canopy cover

**Comment by dlebauer** [comment]
work with Jorge on this

**Comment by Chris-Schnaufer** [comment]
Moving plotclipper rework to Drone Pipeline ticket

**Comment by Chris-Schnaufer** [comment]
https://github.com/AgPipeline
