### ISSUE TITLE
Access to generated data outside of Clowder

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/drone-pipeline#23]
**Please describe your request. Is your feature request related to a problem?**
Clowder may not be the best access mechanism for all people to access the generated data

**Describe the solution you'd like**
Expose generated data through other means

**Describe alternatives you've considered**
N/A

**Additional context**
Globus may be a good mechanism for exposing the data

**Comment by dlebauer** [comment]
maybe irods / cyverse data store?

**Comment by Chris-Schnaufer** [comment]
Closing this as obsolete. This is not a separate task anymore but it being addressed by migration of TERRA REF pipeline to UA and other efforts
