### ISSUE TITLE
Document TravisCI integration

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/drone-pipeline#48]

**Comment by Chris-Schnaufer** [comment]
The document is can be found at https://docs.google.com/document/d/1XluZEZNzYHW6rDXrJOrddhE0lG9lTj1-JvRoKjiN6Kg/edit?usp=sharing

**Comment by dlebauer** [comment]
@dlebauer will review

**Comment by dlebauer** [comment]
Looks good - was there anything in particular that you wanted me to review? Should it be in the repository or the OSF wiki?
