### ISSUE TITLE
Document what December release features are

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/drone-pipeline#66]
Document what features will be available for the December release

**Comment by Chris-Schnaufer** [comment]
The list can be found at: https://docs.google.com/spreadsheets/d/1rQ-n09EnLL4SR6OkvZX0Yx7KICJOSQntVumBijRXq7Y/edit?usp=sharing

**Comment by Chris-Schnaufer** [comment]
David to review

**Comment by dlebauer** [comment]
This list is a good start ... but what will this actually look like when we present it at, e.g., Phenome, or invite collaborators to use it? Will it be operational for someone in the field like Francelino or Duke?

**Comment by Chris-Schnaufer** [comment]
Superseded by #112
