### ISSUE TITLE
Run and test all extractor algorithms from Google Doc

### ISSUE THREAD

**Issue by cmbrown89** [terraref/drone-pipeline#68]
Take extractor algorithms from [google doc](https://docs.google.com/document/d/1cAm5w1Bs6dB1SHgf-HVmwwbebLhbZMUvTkXLtas_-xI/edit?usp=sharing) and add to output extractor table.

**Comment by dlebauer** [comment]
closing - implemented in https://github.com/AgPipeline/transformer-rgb-indices/blob/develop/algorithm_rgb.py
