### ISSUE TITLE
Add drone pipeline extractors to CyVerse

### ISSUE THREAD

**Issue by dlebauer** [terraref/drone-pipeline#80]
For greeness extractor create a tool in the CyVerse DE

given an image, generate a csv file full of values. This will be useful for demonstrating how the extractor works as well as how the DE can be used as a prototyping platform. 

Ask about demoing the new DE interface

**Comment by dlebauer** [comment]
@Chris-Schnaufer can get the basic container going

@julianpistorius can help with integration into CyVerse

**Comment by Chris-Schnaufer** [comment]
Closing this as completed
