### ISSUE TITLE
Write abstract for Drone Pipeline abstract

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/drone-pipeline#93]

**Comment by dlebauer** [comment]
either take a book on scientific writing from my office and / or review the nature abstract template

https://cbs.umn.edu/sites/cbs.umn.edu/files/public/downloads/Annotated_Nature_abstract.pdf

**Comment by KristinaRiemer** [comment]
I can help edit/revise this.

**Comment by Chris-Schnaufer** [comment]
https://docs.google.com/document/d/1tOhEf4L5Gp9NrCfou2adtC1eT3F98KbZXi9808q5UQI/edit?usp=sharing

**Comment by dlebauer** [comment]
Submitted
